-- ============================================================
-- Vape Club Dubai — Production Database Dump
-- Target Host: cPanel / MySQL / MariaDB (5.7+ / 8.0+)
-- Character Set: utf8mb4 / utf8mb4_unicode_ci
-- ============================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ------------------------------------------------------------
-- Table: vcd_categories
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `vcd_categories` (
  `slug` VARCHAR(64) NOT NULL,
  `title` VARCHAR(128) NOT NULL,
  `sub` VARCHAR(255) DEFAULT '',
  `description` TEXT,
  `theme` VARCHAR(64) DEFAULT 'art-emerald',
  `art` VARCHAR(64) DEFAULT 'pack',
  `photo` VARCHAR(255) DEFAULT '',
  PRIMARY KEY (`slug`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `vcd_categories` (`slug`, `title`, `sub`, `description`, `theme`, `art`, `photo`) VALUES ('iluma', 'Heating Device', 'Best heating kit in Dubai', 'Bladeless Smartcore induction devices — ILUMA i PRIME, ILUMA i and ILUMA i ONE. No blade, no cleaning — pure taste from TEREA sticks with up to 3 consecutive uses.', 'art-purple', 'device', 'assets/images/hero-iluma.webp') ON DUPLICATE KEY UPDATE `title`=VALUES(`title`), `description`=VALUES(`description`);
INSERT INTO `vcd_categories` (`slug`, `title`, `sub`, `description`, `theme`, `art`, `photo`) VALUES ('pod', 'Pod Kit', 'Best pod kit in Dubai', 'Rechargeable pod systems by Uwell, Vaporesso & SMOK — pocket-friendly MTL/RDL setups with 2ml GCC-legal pods and all-day batteries.', 'art-navy', 'pod', 'assets/images/cat-pod.jpg') ON DUPLICATE KEY UPDATE `title`=VALUES(`title`), `description`=VALUES(`description`);
INSERT INTO `vcd_categories` (`slug`, `title`, `sub`, `description`, `theme`, `art`, `photo`) VALUES ('disposables', 'Disposable', 'Dubai best disposables', 'Mega-puff disposables up to 12,000 puffs — Vozol, Tugboat, Fummo & Pod Salt. Mesh coil, Type-C charging and ice-cold flavors that never fade.', 'art-rose', 'vape', 'assets/images/hero-vape.png') ON DUPLICATE KEY UPDATE `title`=VALUES(`title`), `description`=VALUES(`description`);
INSERT INTO `vcd_categories` (`slug`, `title`, `sub`, `description`, `theme`, `art`, `photo`) VALUES ('eliquid', 'Saltnic Juice', 'Saltnic vape juice in Dubai', 'Premium 20–50mg salt nic e-liquids — Nasty Juice, Pod Salt and more. Smooth throat hit in ESMA-compliant bottles, 10–60ml.', 'art-purple', 'juice', 'assets/images/cat-juice.jpg') ON DUPLICATE KEY UPDATE `title`=VALUES(`title`), `description`=VALUES(`description`);
INSERT INTO `vcd_categories` (`slug`, `title`, `sub`, `description`, `theme`, `art`, `photo`) VALUES ('terea', 'TEREA Sticks', 'TEREA by country in Dubai', 'Authentic sealed TEREA packs flown in weekly from Indonesia, Japan, Switzerland, Kazakhstan and Italy — batch-code verifiable.', 'art-gold', 'pack', 'assets/images/hero-terea.png') ON DUPLICATE KEY UPDATE `title`=VALUES(`title`), `description`=VALUES(`description`);
INSERT INTO `vcd_categories` (`slug`, `title`, `sub`, `description`, `theme`, `art`, `photo`) VALUES ('terea-id', 'TEREA Indonesia', 'Indonesian TEREA in Dubai', 'Fruity & cooling Indonesian-market TEREA sticks — sealed packs flown in weekly with verifiable batch codes.', 'art-emerald', 'pack', 'assets/images/hero-terea.png') ON DUPLICATE KEY UPDATE `title`=VALUES(`title`), `description`=VALUES(`description`);
INSERT INTO `vcd_categories` (`slug`, `title`, `sub`, `description`, `theme`, `art`, `photo`) VALUES ('terea-jp', 'TEREA Japan', 'Japanese TEREA in Dubai', 'Smooth & rich Japanese-market TEREA sticks — sealed Japan packs with verified batch codes and weekly restock.', 'art-navy', 'pack', 'assets/images/hero-terea.png') ON DUPLICATE KEY UPDATE `title`=VALUES(`title`), `description`=VALUES(`description`);
INSERT INTO `vcd_categories` (`slug`, `title`, `sub`, `description`, `theme`, `art`, `photo`) VALUES ('terea-ch', 'TEREA Swiss', 'Swiss TEREA in Dubai', 'Refined & balanced Swiss-market TEREA sticks — factory-sealed European stock for IQOS ILUMA devices.', 'art-gold', 'pack', 'assets/images/hero-terea.png') ON DUPLICATE KEY UPDATE `title`=VALUES(`title`), `description`=VALUES(`description`);
INSERT INTO `vcd_categories` (`slug`, `title`, `sub`, `description`, `theme`, `art`, `photo`) VALUES ('terea-kz', 'TEREA Kazakhstan', 'Kazakh TEREA in Dubai', 'Bold classic blends from the Kazakhstan market — authentic sealed packs for IQOS ILUMA.', 'art-rose', 'pack', 'assets/images/hero-terea.png') ON DUPLICATE KEY UPDATE `title`=VALUES(`title`), `description`=VALUES(`description`);
INSERT INTO `vcd_categories` (`slug`, `title`, `sub`, `description`, `theme`, `art`, `photo`) VALUES ('terea-it', 'TEREA Italy', 'Italian TEREA in Dubai', 'Aromatic Italian-market TEREA sticks — sealed European packs with verified batch codes.', 'art-amber', 'pack', 'assets/images/hero-terea.png') ON DUPLICATE KEY UPDATE `title`=VALUES(`title`), `description`=VALUES(`description`);

-- ------------------------------------------------------------
-- Table: vcd_products
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `vcd_products` (
  `id` VARCHAR(128) NOT NULL,
  `sku` VARCHAR(64) DEFAULT '',
  `name` VARCHAR(255) NOT NULL,
  `brand` VARCHAR(128) DEFAULT '',
  `cat` VARCHAR(64) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `old_price` DECIMAL(10,2) DEFAULT NULL,
  `stock` ENUM('in', 'low', 'out') NOT NULL DEFAULT 'in',
  `best` TINYINT(1) NOT NULL DEFAULT 0,
  `flavor` VARCHAR(255) DEFAULT '',
  `photo` VARCHAR(255) DEFAULT '',
  `photo_alt` VARCHAR(255) DEFAULT '',
  `gallery` JSON DEFAULT NULL,
  `variants` JSON DEFAULT NULL,
  `specs_table` JSON DEFAULT NULL,
  `box_contents` JSON DEFAULT NULL,
  `description` TEXT,
  `seo_title` VARCHAR(255) DEFAULT '',
  `seo_desc` TEXT,
  `seo_keywords` VARCHAR(255) DEFAULT '',
  `slug` VARCHAR(128) DEFAULT '',
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_cat` (`cat`),
  KEY `idx_brand` (`brand`),
  KEY `idx_stock` (`stock`),
  KEY `idx_best` (`best`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `vcd_products` (`id`, `sku`, `name`, `brand`, `cat`, `price`, `old_price`, `stock`, `best`, `flavor`, `photo`, `photo_alt`, `gallery`, `variants`, `specs_table`, `box_contents`, `description`, `seo_title`, `seo_desc`, `seo_keywords`, `slug`) VALUES ('iluma-prime-remix', 'ILUMA-PRIME-PURPLE-UAE', 'IQOS ILUMA i PRIME Remix — Electric Purple', 'IQOS (Philip Morris International)', 'iluma', 440.0, 520.0, 'in', 1, 'Smartcore Induction · Pause Mode · Touch Screen', 'assets/images/products/iluma_i_prime_purple.jpg', '', '[]', '{"type": "device", "colors": [{"id": "purple", "name": "Electric Purple (Remix)", "hex": "#8B5CF6", "photo": "assets/images/products/iluma_i_prime_purple.jpg"}, {"id": "black", "name": "Obsidian Black", "hex": "#1E293B", "photo": "assets/images/products/iluma_i_one_remix.jpg"}, {"id": "bronze", "name": "Breeze Gold & Bronze", "hex": "#D97706", "photo": "assets/images/products/iluma_i_breeze_blue.jpg"}], "bundles": [{"id": "device_only", "label": "Device Kit Only", "priceDiff": 0, "note": "Complete holder & pocket charger set"}, {"id": "bundle_1pack", "label": "Device + 1x TEREA Pack (+120 AED)", "priceDiff": 120, "note": "Choose any TEREA pack on delivery"}, {"id": "bundle_carton", "label": "Device + 1x TEREA Carton (+1,150 AED)", "priceDiff": 1150, "note": "Full 10-pack carton (200 sticks) · Free 1h Delivery"}]}', '{"Device Model": "IQOS ILUMA i PRIME (Remix Flagship Edition)", "Heating System": "Smartcore Induction System™ (Bladeless)", "Compatible Sticks": "TEREA™ Induction Sticks only (Do not use Heets)", "Consecutive Uses": "Up to 3 uses without holder recharge", "Pocket Charger Capacity": "Up to 20 uses per full charge", "Charging Time": "Approx. 135 minutes via USB-C fast charging", "Holder Touch Screen": "Digital LED battery & puff status indicator", "Pause Mode": "Allows pausing your session for up to 8 minutes", "UAE ESMA Certification": "UAE.S 5030 Compliant & Approved for GCC", "Warranty": "12 Months Official UAE Replacement Warranty"}', '["1x IQOS ILUMA i PRIME Holder", "1x Luxury Anodized Aluminum Pocket Charger", "1x USB Type-C Fast Charging Cable", "1x Official UAE AC Power Adapter", "1x Multilingual User Manual & Warranty Card"]', 'Experience the pinnacle of heated tobacco technology in Dubai. The IQOS ILUMA i PRIME Remix in Electric Purple represents Philip Morris International\'s most advanced innovation. Featuring the revolutionary bladeless Smartcore Induction System™, it heats tobacco from within the sealed TEREA stick without burning it, ensuring zero residue, no blade breakage, and absolutely no cleaning required.

The new touch screen on the holder shows your heating status, remaining puffs, and battery level at a glance. Featuring FlexPuff and Pause Mode, you can pause your session for up to 8 minutes and resume without wasting your stick. Available in Dubai, Sharjah, and Ajman with 1-2 hour express courier dispatch and official 12-month UAE warranty.', '', '', '', 'iluma-prime-remix') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `price`=VALUES(`price`), `photo`=VALUES(`photo`), `gallery`=VALUES(`gallery`), `variants`=VALUES(`variants`);
INSERT INTO `vcd_products` (`id`, `sku`, `name`, `brand`, `cat`, `price`, `old_price`, `stock`, `best`, `flavor`, `photo`, `photo_alt`, `gallery`, `variants`, `specs_table`, `box_contents`, `description`, `seo_title`, `seo_desc`, `seo_keywords`, `slug`) VALUES ('iluma-i-one', 'ILUMA-ONE-BLACK-UAE', 'IQOS ILUMA i ONE — Midnight Black', 'IQOS (Philip Morris International)', 'iluma', 220.0, 260.0, 'in', 0, 'Compact all-in-one · 20 uses per charge', 'assets/images/products/iluma_i_one_remix.jpg', '', '[]', '{"type": "device", "colors": [{"id": "black", "name": "Midnight Black", "hex": "#111827", "photo": "assets/images/products/iluma_i_one_remix.jpg"}, {"id": "purple", "name": "Breeze Purple", "hex": "#8B5CF6", "photo": "assets/images/products/iluma_i_prime_purple.jpg"}, {"id": "blue", "name": "Azure Blue", "hex": "#0284C7", "photo": "assets/images/products/iluma_i_breeze_blue.jpg"}], "bundles": [{"id": "device_only", "label": "Device Kit Only", "priceDiff": 0, "note": "All-in-one pocket unit & USB-C cable"}, {"id": "bundle_1pack", "label": "Device + 1x TEREA Pack (+120 AED)", "priceDiff": 120, "note": "Includes 1 sealed TEREA pack of choice"}, {"id": "bundle_carton", "label": "Device + 1x TEREA Carton (+1,150 AED)", "priceDiff": 1150, "note": "Full 10-pack carton (200 sticks)"}]}', '{"Device Model": "IQOS ILUMA i ONE (All-in-One Compact)", "Heating System": "Smartcore Induction System™ (Bladeless)", "Compatible Sticks": "TEREA™ Induction Sticks", "Uses per Charge": "20 consecutive sessions on single full charge", "Battery Capacity": "Integrated 1728mAh rechargeable lithium cell", "Charging Time": "Approx. 90 minutes via USB-C", "Cleaning Required": "None (Sealed stick leaves zero tobacco crumbs)", "Dimensions": "121.6 x 30.6 x 16.4 mm", "ESMA Compliance": "UAE.S 5030 Certified Legal Nicotine Heating Device"}', '["1x IQOS ILUMA i ONE All-in-One Device", "1x USB Type-C Charging Cable", "1x Power Adapter", "1x UAE Quick Start Manual"]', 'The IQOS ILUMA i ONE Midnight Black is the ultimate on-the-go heated tobacco solution for busy professionals and travelers in Dubai. Packed into a sleek, monolithic pocket device, it delivers 20 uninterrupted sessions on a single full charge without requiring a separate charger case.

Powered by Philip Morris\' bladeless Smartcore Induction technology, each TEREA stick is heated thoroughly and cleanly. No loose tobacco crumbs, no cleaning tools needed, and no smoke smell clinging to your car or clothes. 100% verified authentic stock with UAE fast dispatch.', '', '', '', 'iluma-i-one') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `price`=VALUES(`price`), `photo`=VALUES(`photo`), `gallery`=VALUES(`gallery`), `variants`=VALUES(`variants`);
INSERT INTO `vcd_products` (`id`, `sku`, `name`, `brand`, `cat`, `price`, `old_price`, `stock`, `best`, `flavor`, `photo`, `photo_alt`, `gallery`, `variants`, `specs_table`, `box_contents`, `description`, `seo_title`, `seo_desc`, `seo_keywords`, `slug`) VALUES ('iluma-i-standard', 'ILUMA-STD-BLUE-UAE', 'IQOS ILUMA i Standard — Breeze Blue', 'IQOS (Philip Morris International)', 'iluma', 295.0, 330.0, 'in', 0, 'Classic holder + charger format', 'assets/images/products/iluma_i_breeze_blue.jpg', '', '[]', '{"type": "device", "colors": [{"id": "blue", "name": "Breeze Blue", "hex": "#0284C7", "photo": "assets/images/products/iluma_i_breeze_blue.jpg"}, {"id": "black", "name": "Pebble Black", "hex": "#1E293B", "photo": "assets/images/products/iluma_i_one_remix.jpg"}, {"id": "purple", "name": "Electric Purple", "hex": "#8B5CF6", "photo": "assets/images/products/iluma_i_prime_purple.jpg"}], "bundles": [{"id": "device_only", "label": "Device Kit Only", "priceDiff": 0, "note": "Holder & Pocket Charger"}, {"id": "bundle_1pack", "label": "Device + 1x TEREA Pack (+120 AED)", "priceDiff": 120, "note": "Includes 1 sealed TEREA pack"}, {"id": "bundle_carton", "label": "Device + 1x TEREA Carton (+1,150 AED)", "priceDiff": 1150, "note": "Full 10-pack carton (200 sticks)"}]}', '{"Device Model": "IQOS ILUMA i Standard", "Format": "Ergonomic Holder + Pocket Charger Set", "Heating System": "Smartcore Induction System™ (Bladeless)", "Compatible Sticks": "TEREA™ Sticks only", "Holder Sessions": "2 consecutive uses before returning to pocket charger", "Pocket Charger Capacity": "Charges holder up to 20 times", "Charging Port": "USB Type-C Fast Charge", "Warranty": "12-Month UAE Warranty"}', '["1x IQOS ILUMA i Holder", "1x IQOS ILUMA i Pocket Charger", "1x USB Type-C Cable", "1x AC Power Adapter", "1x User Manual"]', 'The iconic two-piece format, now perfected with Smartcore Induction. The IQOS ILUMA i Standard in Breeze Blue provides the comfortable in-hand feel of a lightweight pen holder paired with an elegant protective charging case. Offering 2 consecutive uses per charge and up to 20 uses from the pocket charger, it is the golden standard of modern tobacco heating in the UAE.', '', '', '', 'iluma-i-standard') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `price`=VALUES(`price`), `photo`=VALUES(`photo`), `gallery`=VALUES(`gallery`), `variants`=VALUES(`variants`);
INSERT INTO `vcd_products` (`id`, `sku`, `name`, `brand`, `cat`, `price`, `old_price`, `stock`, `best`, `flavor`, `photo`, `photo_alt`, `gallery`, `variants`, `specs_table`, `box_contents`, `description`, `seo_title`, `seo_desc`, `seo_keywords`, `slug`) VALUES ('terea-sun-pearl-id', 'TEREA-SUN-PEARL-ID', 'TEREA Sun Pearl — Indonesia Pack', 'TEREA (Philip Morris Indonesia)', 'terea-id', 120.0, 145.0, 'in', 1, 'Watermelon-mint pearl capsule · cooling', 'assets/images/products/terea_sun_pearl_italy.jpg', '', '[]', '{"type": "packSize", "packSizes": [{"id": "single", "label": "Single Pack (20 Sticks)", "price": 120, "old": 145, "note": "1 Pack · 20 Sticks sealed"}, {"id": "carton", "label": "Carton / 10 Packs (200 Sticks)", "price": 1150, "old": 1350, "save": "Save 50 AED", "note": "Full 10-pack sealed carton · Free Express Delivery"}]}', '{"Product Name": "TEREA Sun Pearl Indonesia", "Origin": "Indonesia (PT Philip Morris Indonesia)", "Flavor Profile": "Smooth balanced tobacco with crushable juicy watermelon-mint pearl", "Menthol Intensity": "4 / 5 (After clicking pearl capsule)", "Packaging": "20 heatsticks per pack / 200 per carton", "Compatibility": "IQOS ILUMA, ILUMA ONE, ILUMA PRIME devices ONLY", "Authenticity": "Sealed duty-paid tax band with readable batch code"}', '["1x Sealed Pack of 20 TEREA Sun Pearl Sticks (or 10-pack carton depending on selection)"]', 'TEREA Sun Pearl from Indonesia is Dubai\'s undisputed #1 best-selling click-capsule heatstick. Each stick starts with a rich, toasted Indonesian tobacco aroma. When you press the pearl capsule embedded in the filter, a surge of chilled watermelon essence combined with crisp, frosted mint bursts onto your palate.

Flown in directly from Jakarta weekly in temperature-controlled shipments to guarantee maximum freshness. Zero tobacco fallout, no messy blades, and clean vapor throughout your session.', '', '', '', 'terea-sun-pearl-id') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `price`=VALUES(`price`), `photo`=VALUES(`photo`), `gallery`=VALUES(`gallery`), `variants`=VALUES(`variants`);
INSERT INTO `vcd_products` (`id`, `sku`, `name`, `brand`, `cat`, `price`, `old_price`, `stock`, `best`, `flavor`, `photo`, `photo_alt`, `gallery`, `variants`, `specs_table`, `box_contents`, `description`, `seo_title`, `seo_desc`, `seo_keywords`, `slug`) VALUES ('terea-dimensions-yugen-id', 'TEREA-DIM-YUGEN-ID', 'TEREA Dimensions Yugen — Indonesia', 'TEREA Dimensions Series', 'terea-id', 130.0, NULL, 'in', 0, 'Pear · lavender · soft floral finish', 'assets/images/products/terea_black_green_indonesia.jpg', '', '[]', '{"type": "packSize", "packSizes": [{"id": "single", "label": "Single Pack (20 Sticks)", "price": 130, "old": 150, "note": "1 Pack · 20 Sticks"}, {"id": "carton", "label": "Carton / 10 Packs (200 Sticks)", "price": 1250, "old": 1450, "save": "Save 50 AED", "note": "10 Packs · Free Express Delivery"}]}', '{"Product": "TEREA Dimensions Yugen", "Collection": "Master Chef Collaboration Dimensions Series", "Aroma Profile": "Ripe pear, wild berries, lavender and chilled floral mist", "Tobacco Body": "Light to medium roasted Virginia tobacco", "Cooling Level": "3 / 5 (Crisp soothing menthol finish)", "Compatibility": "IQOS ILUMA series"}', '["1x Sealed Pack of 20 TEREA Dimensions Yugen Sticks"]', 'Co-created with culinary master chefs, TEREA Dimensions Yugen is an exquisite sensory journey. It harmoniously weaves sweet ripe pear with delicate lavender botanicals and subtle berry undertones over a smooth, mellow Indonesian tobacco foundation. A sophisticated choice for discerning heatstick enthusiasts in the UAE.', '', '', '', 'terea-dimensions-yugen-id') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `price`=VALUES(`price`), `photo`=VALUES(`photo`), `gallery`=VALUES(`gallery`), `variants`=VALUES(`variants`);
INSERT INTO `vcd_products` (`id`, `sku`, `name`, `brand`, `cat`, `price`, `old_price`, `stock`, `best`, `flavor`, `photo`, `photo_alt`, `gallery`, `variants`, `specs_table`, `box_contents`, `description`, `seo_title`, `seo_desc`, `seo_keywords`, `slug`) VALUES ('terea-rich-regular-jp', 'TEREA-RICH-REG-JP', 'TEREA Rich Regular — Japan', 'TEREA (Japan Domestic Market)', 'terea-jp', 140.0, 165.0, 'in', 1, 'Deep roasted tobacco · full body', 'assets/images/products/terea_rich_regular_japan.jpg', '', '[]', '{"type": "packSize", "packSizes": [{"id": "single", "label": "Single Pack (20 Sticks)", "price": 140, "old": 165, "note": "1 Pack · 20 Sticks Japan Domestic"}, {"id": "carton", "label": "Carton / 10 Packs (200 Sticks)", "price": 1350, "old": 1550, "save": "Save 50 AED", "note": "Full 10-pack Japan carton · Free Express Delivery"}]}', '{"Product": "TEREA Rich Regular Japan Market", "Origin": "Japan (PMI Japan Domestic Market)", "Aroma Notes": "Deep toasted malt, roasted tobacco leaves, dark cocoa hints", "Body & Intensity": "5 / 5 (Full-bodied traditional tobacco hit)", "Menthol": "0 / 5 (Pure Non-menthol tobacco)", "Compatibility": "IQOS ILUMA devices"}', '["1x Authentic Japan Sealed Pack of 20 TEREA Rich Regular Sticks"]', 'For smokers transitioning to heated tobacco who demand an authentic, deeply satisfying cigarette-like body, TEREA Rich Regular from Japan is the gold standard. Carefully curated for the Japanese domestic market, it uses sun-cured and toasted tobaccos with rich nutty notes and zero artificial aftertaste. Delivered in Dubai within 1-2 hours.', '', '', '', 'terea-rich-regular-jp') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `price`=VALUES(`price`), `photo`=VALUES(`photo`), `gallery`=VALUES(`gallery`), `variants`=VALUES(`variants`);
INSERT INTO `vcd_products` (`id`, `sku`, `name`, `brand`, `cat`, `price`, `old_price`, `stock`, `best`, `flavor`, `photo`, `photo_alt`, `gallery`, `variants`, `specs_table`, `box_contents`, `description`, `seo_title`, `seo_desc`, `seo_keywords`, `slug`) VALUES ('terea-mint-jp', 'TEREA-MINT-JP', 'TEREA Mint — Japan', 'TEREA (Japan Domestic Market)', 'terea-jp', 140.0, 165.0, 'in', 0, 'Crisp double mint · clean finish', 'assets/images/products/terea_oasis_pearl_indonesia.jpg', '', '[]', '{"type": "packSize", "packSizes": [{"id": "single", "label": "Single Pack (20 Sticks)", "price": 140, "old": 165, "note": "1 Pack · 20 Sticks"}, {"id": "carton", "label": "Carton / 10 Packs (200 Sticks)", "price": 1350, "old": 1550, "save": "Save 50 AED", "note": "10 Packs · Free Express Delivery"}]}', '{"Origin": "Japan (Direct Duty Free Import)", "Flavor Type": "Crisp natural spearmint & clean peppermint", "Cooling Level": "4 / 5", "Tobacco Body": "Medium"}', '["1x Japan TEREA Mint Pack (20 sticks)"]', 'Imported straight from Tokyo, TEREA Mint Japan offers a pristine, icy spearmint sensation balanced with a mellow tobacco foundation. Unlike heavy sweet menthols, it leaves your palate feeling refreshed and clean after every puff.', '', '', '', 'terea-mint-jp') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `price`=VALUES(`price`), `photo`=VALUES(`photo`), `gallery`=VALUES(`gallery`), `variants`=VALUES(`variants`);
INSERT INTO `vcd_products` (`id`, `sku`, `name`, `brand`, `cat`, `price`, `old_price`, `stock`, `best`, `flavor`, `photo`, `photo_alt`, `gallery`, `variants`, `specs_table`, `box_contents`, `description`, `seo_title`, `seo_desc`, `seo_keywords`, `slug`) VALUES ('terea-amber-ch', 'TEREA-AMBER-CH', 'TEREA Amber — Switzerland', 'TEREA Swiss Alps Reserve', 'terea-ch', 150.0, 175.0, 'in', 1, 'Woody · nutty · refined aroma', 'assets/images/products/terea_teak_swiss.jpg', '', '[]', '{"type": "packSize", "packSizes": [{"id": "single", "label": "Single Pack (20 Sticks)", "price": 150, "old": 175, "note": "1 Pack · 20 Swiss Sticks"}, {"id": "carton", "label": "Carton / 10 Packs (200 Sticks)", "price": 1450, "old": 1650, "save": "Save 50 AED", "note": "Full 10-pack Swiss carton · Free 1h Delivery"}]}', '{"Origin": "Neuchâtel, Switzerland (PMI R&D Center)", "Flavor Profile": "Toasted woody notes with subtle nutty undertones", "Tobacco Body": "Medium to full (Classic European blend)", "Menthol Level": "0 / 5 (Non-menthol)"}', '["1x Sealed Swiss TEREA Amber Pack (20 Sticks)"]', 'Engineered in Neuchâtel, Switzerland, TEREA Amber represents the pinnacle of European heated tobacco refinement. It delivers a rich, rounded taste with fragrant woody tones and velvety hazelnut nuances. 100% original Swiss import stock in Dubai.', '', '', '', 'terea-amber-ch') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `price`=VALUES(`price`), `photo`=VALUES(`photo`), `gallery`=VALUES(`gallery`), `variants`=VALUES(`variants`);
INSERT INTO `vcd_products` (`id`, `sku`, `name`, `brand`, `cat`, `price`, `old_price`, `stock`, `best`, `flavor`, `photo`, `photo_alt`, `gallery`, `variants`, `specs_table`, `box_contents`, `description`, `seo_title`, `seo_desc`, `seo_keywords`, `slug`) VALUES ('terea-turquoise-ch', 'TEREA-TURQ-CH', 'TEREA Turquoise — Switzerland', 'TEREA Swiss Collection', 'terea-ch', 150.0, NULL, 'low', 0, 'Cool menthol wave · zesty', 'assets/images/products/terea_yellow_swiss.jpg', '', '[]', '{"type": "packSize", "packSizes": [{"id": "single", "label": "Single Pack (20 Sticks)", "price": 150, "old": 170, "note": "1 Pack · 20 Sticks"}, {"id": "carton", "label": "Carton / 10 Packs (200 Sticks)", "price": 1450, "old": 1650, "save": "Save 50 AED", "note": "10 Packs · Free Delivery"}]}', '{"Origin": "Switzerland", "Flavor Profile": "Crisp menthol with citrusy zesty undertone", "Cooling": "3 / 5", "Compatibility": "IQOS ILUMA Series"}', '["1x Swiss TEREA Turquoise Pack (20 Sticks)"]', 'Crisp and revitalizing, TEREA Turquoise from Switzerland brings together a lightly toasted tobacco base with a brisk, soothing menthol wave accented by subtle zesty citrus notes.', '', '', '', 'terea-turquoise-ch') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `price`=VALUES(`price`), `photo`=VALUES(`photo`), `gallery`=VALUES(`gallery`), `variants`=VALUES(`variants`);
INSERT INTO `vcd_products` (`id`, `sku`, `name`, `brand`, `cat`, `price`, `old_price`, `stock`, `best`, `flavor`, `photo`, `photo_alt`, `gallery`, `variants`, `specs_table`, `box_contents`, `description`, `seo_title`, `seo_desc`, `seo_keywords`, `slug`) VALUES ('terea-purple-kz', 'TEREA-PURPLE-KZ', 'TEREA Purple Wave — Kazakhstan', 'TEREA Kazakhstan Collection', 'terea-kz', 115.0, 135.0, 'in', 0, 'Forest berries · menthol twist', 'assets/images/products/terea_purple_kazakhstan.jpg', '', '[]', '{"type": "packSize", "packSizes": [{"id": "single", "label": "Single Pack (20 Sticks)", "price": 115, "old": 135, "note": "1 Pack · 20 Sticks"}, {"id": "carton", "label": "Carton / 10 Packs (200 Sticks)", "price": 1100, "old": 1250, "save": "Save 50 AED", "note": "10 Packs · Best Value · Free 1h Delivery"}]}', '{"Origin": "Kazakhstan (Official PMI Almaty Plant)", "Flavor Profile": "Dark wild forest berries with refreshing menthol breeze", "Cooling": "3.5 / 5", "Compatibility": "All IQOS ILUMA Models"}', '["1x Sealed Kazakhstan TEREA Purple Wave Pack"]', 'A regional favorite across the GCC, TEREA Purple Wave Kazakhstan infuses wild dark forest berries, blueberries, and fragrant alpine botanicals with an icy menthol finish over rich tobacco. Outstanding value and authentic quality in Dubai.', '', '', '', 'terea-purple-kz') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `price`=VALUES(`price`), `photo`=VALUES(`photo`), `gallery`=VALUES(`gallery`), `variants`=VALUES(`variants`);
INSERT INTO `vcd_products` (`id`, `sku`, `name`, `brand`, `cat`, `price`, `old_price`, `stock`, `best`, `flavor`, `photo`, `photo_alt`, `gallery`, `variants`, `specs_table`, `box_contents`, `description`, `seo_title`, `seo_desc`, `seo_keywords`, `slug`) VALUES ('terea-bronze-it', 'TEREA-BRONZE-IT', 'TEREA Bronze — Italy', 'TEREA Italian Reserve', 'terea-it', 135.0, NULL, 'in', 0, 'Cocoa · dried fruit · velvet body', 'assets/images/products/terea_teak_swiss.jpg', '', '[]', '{"type": "packSize", "packSizes": [{"id": "single", "label": "Single Pack (20 Sticks)", "price": 135, "old": 155, "note": "1 Pack · 20 Sticks Italian Blend"}, {"id": "carton", "label": "Carton / 10 Packs (200 Sticks)", "price": 1280, "old": 1450, "save": "Save 70 AED", "note": "Full 10-pack Italian carton · Free Delivery"}]}', '{"Origin": "Bologna, Italy (PMI European Manufacturing)", "Flavor Profile": "Rich cocoa, dried fruits, velvety tobacco body", "Intensity": "4.5 / 5"}', '["1x Italian TEREA Bronze Pack (20 Sticks)"]', 'Straight from Bologna, Italy, TEREA Bronze is a connoisseur\'s blend. Warm roasted tobacco is layered with notes of dark cacao, sun-dried raisins, and a touch of sweetness for a deep, velvety finish.', '', '', '', 'terea-bronze-it') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `price`=VALUES(`price`), `photo`=VALUES(`photo`), `gallery`=VALUES(`gallery`), `variants`=VALUES(`variants`);
INSERT INTO `vcd_products` (`id`, `sku`, `name`, `brand`, `cat`, `price`, `old_price`, `stock`, `best`, `flavor`, `photo`, `photo_alt`, `gallery`, `variants`, `specs_table`, `box_contents`, `description`, `seo_title`, `seo_desc`, `seo_keywords`, `slug`) VALUES ('vozol-gear-10k', 'VOZOL-GEAR-10K', 'Vozol Gear 10000 — Watermelon Ice', 'Vozol Official UAE', 'disposables', 65.0, 85.0, 'in', 1, '10,000 puffs · mesh coil · 50mg', 'assets/images/products/vozol_gear_10000.jpg', '', '[]', '{"type": "vape", "flavors": [{"id": "watermelon_ice", "name": "Watermelon Ice", "note": "Sweet chilled melon slice"}, {"id": "blue_razz", "name": "Blue Razz Ice", "note": "Tangy blueberry raspberry slush"}, {"id": "cool_mint", "name": "Cool Mint", "note": "Ultra-crisp Arctic blast"}, {"id": "strawberry_kiwi", "name": "Strawberry Kiwi", "note": "Juicy ripe summer berries"}, {"id": "mango_peach", "name": "Mango Peach Smoothie", "note": "Tropical nectar blend"}], "strengths": [{"id": "50mg", "label": "50mg (5% Salt Nic)", "note": "Maximum satisfying throat hit"}, {"id": "20mg", "label": "20mg (2% Smooth)", "note": "Gentle, EU-compliant salt nic"}], "bundles": [{"id": "1pc", "label": "1 Piece", "priceDiff": 0, "note": "Individual retail pack"}, {"id": "3pack", "label": "3-Pack Bundle (Save 25 AED)", "priceDiff": 110, "note": "Total 3 vapes (175 AED) · Mix flavors on WhatsApp"}, {"id": "10pack", "label": "Box of 10 (Wholesale 520 AED)", "priceDiff": 455, "note": "Full box · Best price in UAE"}]}', '{"Device Model": "Vozol Gear 10000 Outdoor Series", "Puff Capacity": "Approx. 10,000 Puffs", "Coil Technology": "VAMT Mesh Coil (Zero burnt taste)", "E-Liquid Capacity": "20ml Pre-filled Premium Salt Nic", "Nicotine Strength": "50mg (5%) or 20mg (2%)", "Battery Capacity": "500mAh USB-C Rechargeable", "Special Feature": "Carabiner ring & hygienic silicone mouthpiece protector", "Certification": "ESMA Compliant UAE Import"}', '["1x Vozol Gear 10000 Disposable Vape", "1x Removable Silicone Mouthpiece Cap", "1x Carabiner Clip Hook"]', 'The Vozol Gear 10000 is engineered for endurance and intense flavor delivery. Featuring a rugged outdoor casing with a removable hygienic mouthpiece cap and carabiner hook, it is Dubai\'s favorite high-capacity disposable vape. The advanced VAMT mesh coil maintains silky, dense vapor and vibrant taste from your first draw right down to the 10,000th puff. 45-minute Type-C fast charging ensures you never miss a beat.', '', '', '', 'vozol-gear-10k') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `price`=VALUES(`price`), `photo`=VALUES(`photo`), `gallery`=VALUES(`gallery`), `variants`=VALUES(`variants`);
INSERT INTO `vcd_products` (`id`, `sku`, `name`, `brand`, `cat`, `price`, `old_price`, `stock`, `best`, `flavor`, `photo`, `photo_alt`, `gallery`, `variants`, `specs_table`, `box_contents`, `description`, `seo_title`, `seo_desc`, `seo_keywords`, `slug`) VALUES ('tugboat-evo-4500', 'TUGBOAT-EVO-4500', 'Tugboat EVO 4500 — Mango Aloe', 'Tugboat Vape Dubai', 'disposables', 45.0, 60.0, 'in', 1, '4,500 puffs · 5% salt nic', 'assets/images/products/tugboat_evo_4500.jpg', '', '[]', '{"type": "vape", "flavors": [{"id": "mango_aloe", "name": "Mango Aloe", "note": "Sweet Alphonso mango & soothing aloe"}, {"id": "lush_ice", "name": "Lush Ice", "note": "Crisp iced watermelon"}, {"id": "purple_rain", "name": "Purple Rain", "note": "Mixed forest berries & menthol"}, {"id": "strawberry_banana", "name": "Strawberry Banana", "note": "Creamy tropical fruit smoothie"}], "strengths": [{"id": "50mg", "label": "50mg (5% Salt Nic)", "note": "Classic Tugboat hit"}], "bundles": [{"id": "1pc", "label": "1 Piece (45 AED)", "priceDiff": 0, "note": "Single device"}, {"id": "3pack", "label": "Pack of 3 (120 AED)", "priceDiff": 75, "note": "Save 15 AED"}, {"id": "10pack", "label": "Box of 10 (360 AED)", "priceDiff": 315, "note": "Wholesale UAE Price"}]}', '{"Device Model": "Tugboat EVO 4500", "Puff Count": "4,500 Puffs", "Airflow Control": "Adjustable bottom airflow ring (MTL to RDL)", "Battery": "850mAh Built-in Battery", "E-Liquid Volume": "10ml Pre-filled Salt Nicotine", "Nicotine Strength": "5% (50mg)", "Coil": "1.2 ohm Mesh Coil"}', '["1x Tugboat EVO 4500 Disposable Vape"]', 'Tugboat EVO 4500 is one of the most trusted and consistent disposable vapes in the UAE market. With a built-in airflow control dial on the base, you can toggle between a tight cigarette-style draw and a breezy cloud. Mango Aloe pairs juicy ripe tropical mango with a soothing aloe vera exhale.', '', '', '', 'tugboat-evo-4500') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `price`=VALUES(`price`), `photo`=VALUES(`photo`), `gallery`=VALUES(`gallery`), `variants`=VALUES(`variants`);
INSERT INTO `vcd_products` (`id`, `sku`, `name`, `brand`, `cat`, `price`, `old_price`, `stock`, `best`, `flavor`, `photo`, `photo_alt`, `gallery`, `variants`, `specs_table`, `box_contents`, `description`, `seo_title`, `seo_desc`, `seo_keywords`, `slug`) VALUES ('fummo-prince-12k', 'FUMMO-PRINCE-12K', 'Fummo Prince 12000 — Blue Razz', 'Fummo Dubai', 'disposables', 70.0, 90.0, 'in', 0, '12,000 puffs · Type-C fast charge', 'assets/images/products/fummo_prince_5000.jpg', '', '[]', '{"type": "vape", "flavors": [{"id": "blue_razz", "name": "Blue Razz Ice", "note": "Icy blue raspberries"}, {"id": "watermelon_bubblegum", "name": "Watermelon Bubblegum", "note": "Sweet nostalgic candy"}, {"id": "double_apple", "name": "Double Apple Shisha", "note": "Rich anise & red-green apples"}, {"id": "grape_ice", "name": "Grape Ice", "note": "Sweet chilled Concord grapes"}], "strengths": [{"id": "50mg", "label": "50mg (5% Salt Nic)", "note": "Maximum satisfaction"}, {"id": "20mg", "label": "20mg (2% Smooth)", "note": "Mild smooth vapor"}], "bundles": [{"id": "1pc", "label": "1 Piece (70 AED)", "priceDiff": 0, "note": "Standard unit"}, {"id": "3pack", "label": "3-Pack Bundle (190 AED)", "priceDiff": 120, "note": "Save 20 AED"}]}', '{"Device Model": "Fummo Prince 12000 Smart LED", "Puff Count": "12,000 Puffs", "Screen Display": "Smart LED showing exact battery % and juice level", "Coil": "Dual Mesh Flavor Optimization Coil", "Capacity": "20ml Premium Salt Nic", "Charging": "USB-C Ultra Fast Charge"}', '["1x Fummo Prince 12000 Smart Disposable Vape Device"]', 'Never guess when your vape is running dry again. The Fummo Prince 12000 features a sleek digital display showing real-time battery percentage and remaining e-liquid volume. Dual mesh coil engineering guarantees thick, flavor-packed clouds from dawn till dusk.', '', '', '', 'fummo-prince-12k') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `price`=VALUES(`price`), `photo`=VALUES(`photo`), `gallery`=VALUES(`gallery`), `variants`=VALUES(`variants`);
INSERT INTO `vcd_products` (`id`, `sku`, `name`, `brand`, `cat`, `price`, `old_price`, `stock`, `best`, `flavor`, `photo`, `photo_alt`, `gallery`, `variants`, `specs_table`, `box_contents`, `description`, `seo_title`, `seo_desc`, `seo_keywords`, `slug`) VALUES ('podsalt-go-2500', 'PODSALT-GO-2500', 'Pod Salt Go 2500 — Double Apple', 'Pod Salt UK', 'disposables', 30.0, 40.0, 'low', 0, '2,500 puffs · 20mg smooth salt', 'assets/images/products/pod_salt_go_2500.jpg', '', '[]', '{"type": "vape", "flavors": [{"id": "double_apple", "name": "Double Apple Shisha", "note": "Authentic Middle Eastern double apple"}, {"id": "cuban_creme", "name": "Cuban Creme Cigar", "note": "Rich Cuban cigar with vanilla cream"}, {"id": "mixed_berries", "name": "Mixed Berries Ice", "note": "Sweet berries with cool frost"}], "strengths": [{"id": "20mg", "label": "20mg (2% British Salt Nic)", "note": "Award-winning smooth nicotine salt"}], "bundles": [{"id": "1pc", "label": "1 Piece (30 AED)", "priceDiff": 0, "note": "Compact pocket vape"}, {"id": "5pack", "label": "Pack of 5 (135 AED)", "priceDiff": 105, "note": "Save 15 AED"}]}', '{"Manufacturer": "Pod Salt (United Kingdom)", "Puff Count": "2,500 Puffs", "Nicotine Type": "Proprietary Nicotine Salt Formula (UK Lab Tested)", "Nicotine Strength": "20mg/ml (2%)", "Compliance": "ESMA and TPD Certified"}', '["1x Pod Salt Go 2500 Disposable Vape"]', 'Formulated in Great Britain with award-winning nicotine salt liquid, Pod Salt Go 2500 delivers exceptionally smooth satisfaction without the harsh throat bite. Double Apple captures authentic shisha aromas of crisp red and tart green apples with gentle anise spice.', '', '', '', 'podsalt-go-2500') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `price`=VALUES(`price`), `photo`=VALUES(`photo`), `gallery`=VALUES(`gallery`), `variants`=VALUES(`variants`);
INSERT INTO `vcd_products` (`id`, `sku`, `name`, `brand`, `cat`, `price`, `old_price`, `stock`, `best`, `flavor`, `photo`, `photo_alt`, `gallery`, `variants`, `specs_table`, `box_contents`, `description`, `seo_title`, `seo_desc`, `seo_keywords`, `slug`) VALUES ('caliburn-g3', 'CALIBURN-G3-SILVER', 'Uwell Caliburn G3 Pod Kit — Silver', 'Uwell Official', 'pod', 140.0, 165.0, 'in', 0, '25W · 900mAh · top-fill pods', 'assets/images/cat-pod.jpg', '', '[]', '{"type": "podKit", "colors": [{"id": "silver", "name": "Metallic Silver", "hex": "#E2E8F0", "photo": "assets/images/cat-pod.jpg"}, {"id": "black", "name": "Midnight Black", "hex": "#0F172A", "photo": "assets/images/products/iluma_i_one_remix.jpg"}, {"id": "blue", "name": "Cobalt Blue", "hex": "#1D4ED8", "photo": "assets/images/products/iluma_i_breeze_blue.jpg"}], "resistance": [{"id": "0.6ohm", "label": "0.6Ω Meshed Pod (RDL / Freebase)", "note": "Warm cloud & rich vapor"}, {"id": "0.9ohm", "label": "0.9Ω Meshed Pod (MTL / Salt Nic)", "note": "Tight draw & optimal nicotine hit"}], "bundles": [{"id": "kit_only", "label": "Standard Kit Only", "priceDiff": 0, "note": "Includes device + 2 pods"}, {"id": "kit_plus_pods", "label": "Kit + 4x Extra Replacement Pods (+55 AED)", "priceDiff": 55, "note": "Complete full-month setup"}]}', '{"Device Model": "Uwell Caliburn G3 Pod System", "Maximum Output": "Up to 25W adjustable wattage", "Battery Capacity": "900mAh internal battery", "Pod Resistance Options": "0.6Ω and 0.9Ω integrated coil pods", "Pod Capacity": "2ml (GCC & ESMA legal anti-leak top fill)", "Firing Modes": "Button fire & auto-draw activation", "OLED Screen": "Shows wattage, battery bar, puff counter, coil resistance"}', '["1x Uwell Caliburn G3 Device", "1x 0.6Ω Caliburn G3 Meshed Pod", "1x 0.9Ω Caliburn G3 Meshed Pod", "1x Type-C Fast Charging Cable", "1x User Manual"]', 'The Uwell Caliburn G3 is the undisputed benchmark of refillable pod kits. Upgraded with a crisp OLED display, adjustable power up to 25W, and ultrasonic welded anti-leak pods, it delivers unmatched flavor fidelity for both Nic Salts and Freebase e-liquids. Perfect for UAE vapers who want full control over their nicotine and coil resistance.', '', '', '', 'caliburn-g3') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `price`=VALUES(`price`), `photo`=VALUES(`photo`), `gallery`=VALUES(`gallery`), `variants`=VALUES(`variants`);
INSERT INTO `vcd_products` (`id`, `sku`, `name`, `brand`, `cat`, `price`, `old_price`, `stock`, `best`, `flavor`, `photo`, `photo_alt`, `gallery`, `variants`, `specs_table`, `box_contents`, `description`, `seo_title`, `seo_desc`, `seo_keywords`, `slug`) VALUES ('nasty-bad-blood', 'NASTY-BAD-BLOOD-60ML', 'Nasty Juice 60ml — Bad Blood 3mg', 'Nasty Juice Worldwide', 'eliquid', 55.0, 70.0, 'in', 0, 'Blackcurrant · subtle mint', 'assets/images/cat-juice.jpg', '', '[]', '{"type": "juice", "strengths": [{"id": "3mg", "label": "3mg (Sub-Ohm Clouds)", "note": "Light throat hit for high wattage"}, {"id": "6mg", "label": "6mg (Medium Hit)", "note": "Balanced satisfaction"}, {"id": "35mg_salt", "label": "35mg Salt Nic (30ml Pod Bottle)", "note": "Special salt nic formulation"}, {"id": "50mg_salt", "label": "50mg Salt Nic (30ml Pod Bottle)", "note": "Maximum nicotine hit for pod systems"}], "bundles": [{"id": "1bottle", "label": "1 Bottle (55 AED)", "priceDiff": 0, "note": "Official tamper-sealed bottle"}, {"id": "2pack", "label": "Twin Pack (2x Bottles — 95 AED)", "priceDiff": 40, "note": "Save 15 AED"}]}', '{"Brand": "Nasty Juice (Malaysia)", "Flavor Profile": "Sweet blackcurrant berries with subtle cooling mint", "VG / PG Ratio": "70% VG / 30% PG (Rich dense clouds)", "Bottle Size": "60ml Chubby Gorilla childproof bottle", "Nicotine Quality": "USP Pharmaceutical Grade Nicotine", "Compliance": "UAE ESMA Approved & Certified"}', '["1x 60ml Tamper-Evident Sealed Bottle of Nasty Juice Bad Blood"]', 'One of the most celebrated e-liquids in vaping history, Nasty Juice Bad Blood blends the earthy sweetness of freshly picked ripe blackcurrants with a delicate, refreshing hint of mint. Smooth on the inhale and delightfully aromatic on the exhale. Formulated with 70/30 VG/PG for magnificent cloud production in Dubai.', '', '', '', 'nasty-bad-blood') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `price`=VALUES(`price`), `photo`=VALUES(`photo`), `gallery`=VALUES(`gallery`), `variants`=VALUES(`variants`);

-- ------------------------------------------------------------
-- Table: vcd_settings
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `vcd_settings` (
  `setting_key` VARCHAR(64) NOT NULL,
  `setting_value` TEXT,
  PRIMARY KEY (`setting_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `vcd_settings` (`setting_key`, `setting_value`) VALUES ('brand_name', 'VAPE CLUB') ON DUPLICATE KEY UPDATE `setting_value`=VALUES(`setting_value`);
INSERT INTO `vcd_settings` (`setting_key`, `setting_value`) VALUES ('brand_tagline', 'Dubai · IQOS UAE') ON DUPLICATE KEY UPDATE `setting_value`=VALUES(`setting_value`);
INSERT INTO `vcd_settings` (`setting_key`, `setting_value`) VALUES ('logo_type', 'icon') ON DUPLICATE KEY UPDATE `setting_value`=VALUES(`setting_value`);
INSERT INTO `vcd_settings` (`setting_key`, `setting_value`) VALUES ('logo_image', '') ON DUPLICATE KEY UPDATE `setting_value`=VALUES(`setting_value`);
INSERT INTO `vcd_settings` (`setting_key`, `setting_value`) VALUES ('logo_dark_image', '') ON DUPLICATE KEY UPDATE `setting_value`=VALUES(`setting_value`);
INSERT INTO `vcd_settings` (`setting_key`, `setting_value`) VALUES ('favicon_image', '') ON DUPLICATE KEY UPDATE `setting_value`=VALUES(`setting_value`);
INSERT INTO `vcd_settings` (`setting_key`, `setting_value`) VALUES ('delivery_time', '1-2 Hour Express Delivery in Dubai & Sharjah') ON DUPLICATE KEY UPDATE `setting_value`=VALUES(`setting_value`);
INSERT INTO `vcd_settings` (`setting_key`, `setting_value`) VALUES ('brand_footer_note', 'Dubai premium destination for original IQOS, TEREA and disposable vapes — delivered faster than shisha arrives.') ON DUPLICATE KEY UPDATE `setting_value`=VALUES(`setting_value`);
INSERT INTO `vcd_settings` (`setting_key`, `setting_value`) VALUES ('wa_number', '971562848450') ON DUPLICATE KEY UPDATE `setting_value`=VALUES(`setting_value`);
INSERT INTO `vcd_settings` (`setting_key`, `setting_value`) VALUES ('phone_display', '+971 56 284 8450') ON DUPLICATE KEY UPDATE `setting_value`=VALUES(`setting_value`);
INSERT INTO `vcd_settings` (`setting_key`, `setting_value`) VALUES ('phone_tel', '+971562848450') ON DUPLICATE KEY UPDATE `setting_value`=VALUES(`setting_value`);
INSERT INTO `vcd_settings` (`setting_key`, `setting_value`) VALUES ('email', 'orders@vapeclubdubai.ae') ON DUPLICATE KEY UPDATE `setting_value`=VALUES(`setting_value`);
INSERT INTO `vcd_settings` (`setting_key`, `setting_value`) VALUES ('address', 'International City, Dragon Mart, Dubai') ON DUPLICATE KEY UPDATE `setting_value`=VALUES(`setting_value`);
INSERT INTO `vcd_settings` (`setting_key`, `setting_value`) VALUES ('maps_url', 'https://maps.google.com/?q=Dragon+Mart+Dubai') ON DUPLICATE KEY UPDATE `setting_value`=VALUES(`setting_value`);
INSERT INTO `vcd_settings` (`setting_key`, `setting_value`) VALUES ('instagram_url', 'https://instagram.com') ON DUPLICATE KEY UPDATE `setting_value`=VALUES(`setting_value`);
INSERT INTO `vcd_settings` (`setting_key`, `setting_value`) VALUES ('telegram_url', 'https://t.me/iqosaibot') ON DUPLICATE KEY UPDATE `setting_value`=VALUES(`setting_value`);
INSERT INTO `vcd_settings` (`setting_key`, `setting_value`) VALUES ('telegram_bot_username', '@iqosaibot') ON DUPLICATE KEY UPDATE `setting_value`=VALUES(`setting_value`);
INSERT INTO `vcd_settings` (`setting_key`, `setting_value`) VALUES ('telegram_bot_token', '8857079780:AAHNOhHo_aB7NPaoBBpN9uWymsgzJRZw_zU') ON DUPLICATE KEY UPDATE `setting_value`=VALUES(`setting_value`);
INSERT INTO `vcd_settings` (`setting_key`, `setting_value`) VALUES ('telegram_chat_id', '1827362508') ON DUPLICATE KEY UPDATE `setting_value`=VALUES(`setting_value`);
INSERT INTO `vcd_settings` (`setting_key`, `setting_value`) VALUES ('telegram_alerts_enabled', 1) ON DUPLICATE KEY UPDATE `setting_value`=VALUES(`setting_value`);
INSERT INTO `vcd_settings` (`setting_key`, `setting_value`) VALUES ('telegram_order_alerts_enabled', 1) ON DUPLICATE KEY UPDATE `setting_value`=VALUES(`setting_value`);
INSERT INTO `vcd_settings` (`setting_key`, `setting_value`) VALUES ('telegram_vip_alerts_enabled', 1) ON DUPLICATE KEY UPDATE `setting_value`=VALUES(`setting_value`);
INSERT INTO `vcd_settings` (`setting_key`, `setting_value`) VALUES ('telegram_traffic_alerts_enabled', 1) ON DUPLICATE KEY UPDATE `setting_value`=VALUES(`setting_value`);
INSERT INTO `vcd_settings` (`setting_key`, `setting_value`) VALUES ('telegram_2way_chat_enabled', 1) ON DUPLICATE KEY UPDATE `setting_value`=VALUES(`setting_value`);
INSERT INTO `vcd_settings` (`setting_key`, `setting_value`) VALUES ('wa_concierge_name', 'Vape Club Dubai Concierge') ON DUPLICATE KEY UPDATE `setting_value`=VALUES(`setting_value`);
INSERT INTO `vcd_settings` (`setting_key`, `setting_value`) VALUES ('wa_concierge_avatar', 'assets/images/icons/favicon-32.png') ON DUPLICATE KEY UPDATE `setting_value`=VALUES(`setting_value`);
INSERT INTO `vcd_settings` (`setting_key`, `setting_value`) VALUES ('facebook_url', 'https://facebook.com/vapeclubdubai') ON DUPLICATE KEY UPDATE `setting_value`=VALUES(`setting_value`);
INSERT INTO `vcd_settings` (`setting_key`, `setting_value`) VALUES ('tiktok_url', '') ON DUPLICATE KEY UPDATE `setting_value`=VALUES(`setting_value`);
INSERT INTO `vcd_settings` (`setting_key`, `setting_value`) VALUES ('currency', 'AED') ON DUPLICATE KEY UPDATE `setting_value`=VALUES(`setting_value`);
INSERT INTO `vcd_settings` (`setting_key`, `setting_value`) VALUES ('delivery_fee', 20) ON DUPLICATE KEY UPDATE `setting_value`=VALUES(`setting_value`);
INSERT INTO `vcd_settings` (`setting_key`, `setting_value`) VALUES ('free_ship_threshold', 450) ON DUPLICATE KEY UPDATE `setting_value`=VALUES(`setting_value`);
INSERT INTO `vcd_settings` (`setting_key`, `setting_value`) VALUES ('qty_cap', 20) ON DUPLICATE KEY UPDATE `setting_value`=VALUES(`setting_value`);
INSERT INTO `vcd_settings` (`setting_key`, `setting_value`) VALUES ('order_prefix', 'VCD') ON DUPLICATE KEY UPDATE `setting_value`=VALUES(`setting_value`);
INSERT INTO `vcd_settings` (`setting_key`, `setting_value`) VALUES ('rating_value', '4.9') ON DUPLICATE KEY UPDATE `setting_value`=VALUES(`setting_value`);
INSERT INTO `vcd_settings` (`setting_key`, `setting_value`) VALUES ('rating_count', '214') ON DUPLICATE KEY UPDATE `setting_value`=VALUES(`setting_value`);
INSERT INTO `vcd_settings` (`setting_key`, `setting_value`) VALUES ('show_rating', 1) ON DUPLICATE KEY UPDATE `setting_value`=VALUES(`setting_value`);
INSERT INTO `vcd_settings` (`setting_key`, `setting_value`) VALUES ('theme_color', '#070A0F') ON DUPLICATE KEY UPDATE `setting_value`=VALUES(`setting_value`);
INSERT INTO `vcd_settings` (`setting_key`, `setting_value`) VALUES ('copyright', '© 2026 Vape Club Dubai') ON DUPLICATE KEY UPDATE `setting_value`=VALUES(`setting_value`);
INSERT INTO `vcd_settings` (`setting_key`, `setting_value`) VALUES ('hours', '["Daily 10:00 AM – 12:00 AM", "Express dispatch until 11:00 PM"]') ON DUPLICATE KEY UPDATE `setting_value`=VALUES(`setting_value`);
INSERT INTO `vcd_settings` (`setting_key`, `setting_value`) VALUES ('payment_badges', '["COD", "MASTERCARD", "VISA", "APPLE PAY", "SAMSUNG PAY"]') ON DUPLICATE KEY UPDATE `setting_value`=VALUES(`setting_value`);
INSERT INTO `vcd_settings` (`setting_key`, `setting_value`) VALUES ('legal_warning', 'This product contains nicotine. Nicotine is an addictive chemical. Sale to persons under 18 is prohibited under UAE federal law. All products are ESMA certified. Keep away from children and pets.') ON DUPLICATE KEY UPDATE `setting_value`=VALUES(`setting_value`);
INSERT INTO `vcd_settings` (`setting_key`, `setting_value`) VALUES ('legal_links', '["Privacy Policy", "Terms of Service", "Returns & Warranty", "UAE Compliance"]') ON DUPLICATE KEY UPDATE `setting_value`=VALUES(`setting_value`);
INSERT INTO `vcd_settings` (`setting_key`, `setting_value`) VALUES ('wa_msg_assistance', 'Hello Vape Club Dubai! I need assistance.') ON DUPLICATE KEY UPDATE `setting_value`=VALUES(`setting_value`);
INSERT INTO `vcd_settings` (`setting_key`, `setting_value`) VALUES ('wa_msg_order', 'Hello Vape Club Dubai! I want to order.') ON DUPLICATE KEY UPDATE `setting_value`=VALUES(`setting_value`);
INSERT INTO `vcd_settings` (`setting_key`, `setting_value`) VALUES ('wa_msg_question', 'Hello Vape Club Dubai! I have a question about a product.') ON DUPLICATE KEY UPDATE `setting_value`=VALUES(`setting_value`);

-- ------------------------------------------------------------
-- Table: vcd_admin_users
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `vcd_admin_users` (
  `id` VARCHAR(64) NOT NULL,
  `username` VARCHAR(64) NOT NULL UNIQUE,
  `password_hash` VARCHAR(255) NOT NULL,
  `name` VARCHAR(128) NOT NULL,
  `role` ENUM('admin', 'editor', 'author') NOT NULL DEFAULT 'admin',
  `phone` VARCHAR(32) DEFAULT '',
  `status` ENUM('active', 'suspended') NOT NULL DEFAULT 'active',
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `vcd_admin_users` (`id`, `username`, `password_hash`, `name`, `role`, `phone`, `status`) VALUES ('usr_admin', 'admin', '$2y$10$dxLpPbsGZxYZqACPQY4JJuZZU7XItfwTNKp85ZWAVZP5uZWMARFHO', 'Super Admin', 'admin', '+971 50 123 4567', 'active') ON DUPLICATE KEY UPDATE `password_hash`=VALUES(`password_hash`);
INSERT INTO `vcd_admin_users` (`id`, `username`, `password_hash`, `name`, `role`, `phone`, `status`) VALUES ('usr_admin', 'admin', '$2y$10$dxLpPbsGZxYZqACPQY4JJuZZU7XItfwTNKp85ZWAVZP5uZWMARFHO', 'Super Admin', 'admin', '+971 50 123 4567', 'active') ON DUPLICATE KEY UPDATE `password_hash`=VALUES(`password_hash`), `role`=VALUES(`role`);

-- ------------------------------------------------------------
-- Table: vcd_orders
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `vcd_orders` (
  `id` VARCHAR(64) NOT NULL,
  `customer_name` VARCHAR(128) NOT NULL,
  `phone` VARCHAR(32) NOT NULL,
  `emirate` VARCHAR(64) DEFAULT 'Dubai',
  `address` TEXT,
  `payment_method` VARCHAR(64) DEFAULT 'cod',
  `notes` TEXT,
  `items` JSON NOT NULL,
  `total_aed` DECIMAL(10,2) NOT NULL,
  `status` ENUM('new', 'confirmed', 'out_for_delivery', 'delivered', 'cancelled') NOT NULL DEFAULT 'new',
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------------------------------------------------------------
-- Table: vcd_leads
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `vcd_leads` (
  `id` VARCHAR(64) NOT NULL,
  `phone` VARCHAR(32) NOT NULL,
  `name` VARCHAR(128) DEFAULT '',
  `source` VARCHAR(64) DEFAULT 'whatsapp_modal',
  `initial_product` VARCHAR(128) DEFAULT '',
  `chat_history` JSON DEFAULT NULL,
  `status` ENUM('open', 'contacted', 'converted', 'closed') NOT NULL DEFAULT 'open',
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


SET FOREIGN_KEY_CHECKS = 1;
-- Dump complete.